In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

2024-04-11 00:38:57.564348: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
#generate some random data
import numpy as np
X = np.random.random((1000, 1000))
y = np.random.randint(0, 2, 1000)

In [2]:
#preparing the data

X_df = pd.read_csv('../../data/presence_matrices/Campylobacter_coli_presence_absence.csv', index_col=0)
y_df= pd.read_csv('../../data/phenotypes/Campylobacter_coli_ciprofloxacin.csv', index_col=0)


X_df = X_df.sort_index()
y_df = y_df.sort_index()

y_indices=list(y_df.index)
X_indices=list(X_df.index)

#intersection
intersection = [i for i in y_indices if i in X_indices]
y_df = y_df.loc[intersection]
X_df = X_df.loc[intersection]

X = X_df.values
y = y_df.values

In [3]:
#build a vanilla neural network that takes as inputs 1000 vector features
#and outputs a single binary value

#build the model
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(X.shape[1], activation='relu', input_shape=(X.shape[1],)),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

#compile the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

#train the model
model.fit(X, y, epochs=10, batch_size=32)

2024-04-11 00:39:07.890417: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


Epoch 1/10
9/9 [==============================] - 9s 589ms/step - loss: 10.4190 - accuracy: 0.6105
Epoch 2/10
9/9 [==============================] - 5s 609ms/step - loss: 3.3985 - accuracy: 0.7528
Epoch 3/10
9/9 [==============================] - 5s 576ms/step - loss: 1.6419 - accuracy: 0.8015
Epoch 4/10
9/9 [==============================] - 5s 558ms/step - loss: 0.5512 - accuracy: 0.8277
Epoch 5/10
9/9 [==============================] - 5s 562ms/step - loss: 0.2817 - accuracy: 0.8764
Epoch 6/10
9/9 [==============================] - 5s 573ms/step - loss: 0.2195 - accuracy: 0.9026
Epoch 7/10
9/9 [==============================] - 5s 559ms/step - loss: 0.1685 - accuracy: 0.9251
Epoch 8/10
9/9 [==============================] - 5s 547ms/step - loss: 0.1502 - accuracy: 0.9176
Epoch 9/10
9/9 [==============================] - 5s 578ms/step - loss: 0.0998 - accuracy: 0.9775
Epoch 10/10
9/9 [==============================] - 5s 567ms/step - loss: 0.1013 - accuracy: 0.9625


In [4]:
weights = model.get_weights()

In [6]:
#make weights a df


[array([[ 0.00902543, -0.0043931 ,  0.00673736, ..., -0.02381347,
          0.0077692 , -0.00483729],
        [-0.00937063, -0.01432302,  0.01316896, ...,  0.00273977,
         -0.0127153 , -0.00193484],
        [-0.02236633, -0.02701769,  0.01745652, ...,  0.0108552 ,
          0.00556985, -0.00235236],
        ...,
        [ 0.01706709,  0.00168423,  0.00395518, ...,  0.01264294,
          0.00602033, -0.0095194 ],
        [ 0.01074206, -0.01042698, -0.00795635, ...,  0.00239265,
          0.00662425,  0.0132366 ],
        [ 0.01686734, -0.00767862, -0.00555196, ..., -0.01843196,
          0.00045524, -0.00438922]], dtype=float32),
 array([-0.00541369, -0.00163097, -0.00596189, ..., -0.00599686,
         0.        ,  0.        ], dtype=float32),
 array([[-2.0244168e-02],
        [ 7.8427474e-05],
        [ 2.1216610e-02],
        ...,
        [ 6.4173290e-03],
        [-1.7455613e-02],
        [ 2.5150208e-02]], dtype=float32),
 array([-0.0020129], dtype=float32)]

In [ ]:
np.max(weights[0])

In [4]:
model.save('test_1_real_data.h5')

# #get weights of the model
#load the model
# model=tf.keras.models.load_model('test_1_real_data.h5')
# weights = model.get_weights()
# print(np.max(weights[0]))

: 